-- StudyHub v2.2 - Supabase/PostgreSQL schema
-- Spusti celý súbor v Supabase SQL Editore.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'student' check (role in ('student','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create table if not exists public.subjects (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  short_name text not null,
  name text not null,
  description text not null default '',
  status text not null default 'pripravovane'
    check (status in ('hotove','rozpracovane','pripravovane')),
  href text not null,
  color text,
  visible boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.materials (
  id uuid primary key default gen_random_uuid(),
  subject_id uuid not null references public.subjects(id) on delete cascade,
  title text not null,
  type text not null default 'poznamka',
  description text not null default '',
  url text,
  visible boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_questions (
  id uuid primary key default gen_random_uuid(),
  subject_id uuid not null references public.subjects(id) on delete cascade,
  question text not null,
  answers jsonb not null default '[]'::jsonb,
  explanation text not null default '',
  visible boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quiz_questions_answers_array check (jsonb_typeof(answers) = 'array')
);

create table if not exists public.roadmap_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null default '',
  status text not null default 'napady'
    check (status in ('napady','planovane','pracuje_sa','hotove')),
  priority text not null default 'stredna'
    check (priority in ('nizka','stredna','vysoka')),
  subject text,
  item_type text not null default 'funkcia',
  target_date text,
  visible boolean not null default true,
  sort_order integer not null default 100,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.changelog_entries (
  id uuid primary key default gen_random_uuid(),
  version text not null,
  release_date date not null default current_date,
  change_type text not null default 'new'
    check (change_type in ('new','changed','fixed')),
  title text not null,
  description text not null default '',
  visible boolean not null default true,
  sort_order integer not null default 100,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null default current_date,
  activity_type text not null default 'study',
  created_at timestamptz not null default now(),
  unique (user_id, activity_date, activity_type)
);

drop trigger if exists subjects_updated_at on public.subjects;
create trigger subjects_updated_at before update on public.subjects
for each row execute procedure public.set_updated_at();

drop trigger if exists materials_updated_at on public.materials;
create trigger materials_updated_at before update on public.materials
for each row execute procedure public.set_updated_at();

drop trigger if exists quiz_questions_updated_at on public.quiz_questions;
create trigger quiz_questions_updated_at before update on public.quiz_questions
for each row execute procedure public.set_updated_at();

drop trigger if exists roadmap_items_updated_at on public.roadmap_items;
create trigger roadmap_items_updated_at before update on public.roadmap_items
for each row execute procedure public.set_updated_at();

drop trigger if exists changelog_entries_updated_at on public.changelog_entries;
create trigger changelog_entries_updated_at before update on public.changelog_entries
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.materials enable row level security;
alter table public.quiz_questions enable row level security;
alter table public.roadmap_items enable row level security;
alter table public.changelog_entries enable row level security;
alter table public.user_activity enable row level security;

revoke all on public.profiles, public.subjects, public.materials, public.quiz_questions,
  public.roadmap_items, public.changelog_entries, public.user_activity
from anon, authenticated;

grant select on public.subjects, public.materials,
  public.roadmap_items, public.changelog_entries to anon, authenticated;

grant select on public.profiles, public.quiz_questions to authenticated;
grant insert, update, delete on public.subjects, public.materials, public.quiz_questions,
  public.roadmap_items, public.changelog_entries to authenticated;
grant select, insert on public.user_activity to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "subjects_public_read" on public.subjects;
create policy "subjects_public_read"
on public.subjects for select to anon, authenticated
using (visible = true or public.is_admin());

drop policy if exists "subjects_admin_insert" on public.subjects;
create policy "subjects_admin_insert"
on public.subjects for insert to authenticated
with check (public.is_admin());

drop policy if exists "subjects_admin_update" on public.subjects;
create policy "subjects_admin_update"
on public.subjects for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "subjects_admin_delete" on public.subjects;
create policy "subjects_admin_delete"
on public.subjects for delete to authenticated
using (public.is_admin());

drop policy if exists "materials_public_read" on public.materials;
create policy "materials_public_read"
on public.materials for select to anon, authenticated
using (visible = true or public.is_admin());

drop policy if exists "materials_admin_insert" on public.materials;
create policy "materials_admin_insert"
on public.materials for insert to authenticated
with check (public.is_admin());

drop policy if exists "materials_admin_update" on public.materials;
create policy "materials_admin_update"
on public.materials for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "materials_admin_delete" on public.materials;
create policy "materials_admin_delete"
on public.materials for delete to authenticated
using (public.is_admin());

drop policy if exists "questions_public_read" on public.quiz_questions;
drop policy if exists "questions_admin_read" on public.quiz_questions;
create policy "questions_admin_read"
on public.quiz_questions for select to authenticated
using (public.is_admin());

drop policy if exists "questions_admin_insert" on public.quiz_questions;
create policy "questions_admin_insert"
on public.quiz_questions for insert to authenticated
with check (public.is_admin());

drop policy if exists "questions_admin_update" on public.quiz_questions;
create policy "questions_admin_update"
on public.quiz_questions for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "questions_admin_delete" on public.quiz_questions;
create policy "questions_admin_delete"
on public.quiz_questions for delete to authenticated
using (public.is_admin());

drop policy if exists "roadmap_public_read" on public.roadmap_items;
create policy "roadmap_public_read"
on public.roadmap_items for select to anon, authenticated
using (visible = true or public.is_admin());

drop policy if exists "roadmap_admin_all" on public.roadmap_items;
create policy "roadmap_admin_all"
on public.roadmap_items for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "changelog_public_read" on public.changelog_entries;
create policy "changelog_public_read"
on public.changelog_entries for select to anon, authenticated
using (visible = true or public.is_admin());

drop policy if exists "changelog_admin_all" on public.changelog_entries;
create policy "changelog_admin_all"
on public.changelog_entries for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists "activity_select_own" on public.user_activity;
create policy "activity_select_own"
on public.user_activity for select to authenticated
using (user_id = auth.uid());

drop policy if exists "activity_insert_own" on public.user_activity;
create policy "activity_insert_own"
on public.user_activity for insert to authenticated
with check (user_id = auth.uid());

insert into public.subjects (slug, short_name, name, description, status, href, color, visible, sort_order)
values
('vvs','VVS','Vývoj vstavaných systémov','ESP32, MicroPython, senzory, displeje, web server a robotika.','rozpracovane','subjects/vvs.html','#34d399',true,10),
('msd','MSD','Metódy spracovania dát','Excel, časové rady, Fourierova transformácia, pravdepodobnosť a rozdelenia.','rozpracovane','subjects/msd.html','#22d3ee',true,20),
('mat','MAT','Matematika','Diferenciálne rovnice, rady, Fourierov rad a funkcie dvoch premenných.','rozpracovane','subjects/mat.html','#a78bfa',true,30),
('ccna','NET','Cisco / CCNA','Subnetting, VLSM, VLAN, routing, Packet Tracer, DNS a DHCP.','rozpracovane','subjects/ccna.html','#3b82f6',true,40),
('linux','LNX','Linux Essentials','Príkazový riadok, súbory, adresáre, práva, pipe, redirect a finálny kvíz.','hotove','subjects/linux.html','#65d4f2',true,50),
('java','JAVA','Informatika / Java','OOP, dedičnosť, polymorfizmus, výnimky, generiká, UML a projekty.','rozpracovane','subjects/java.html','#fb923c',true,60),
('fyzika','FYZ','Fyzika','Vektory, kinematika, dynamika, moment zotrvačnosti, Steinerova veta, kyvadlo a merania.','hotove','subjects/fyzika.html','#f59e0b',true,70),
('tlac3d','3D','3D tlač','Aditívna výroba, FDM/FFF, SLA, SLS, slicer a semestrálny projekt.','pripravovane','subjects/3d-tlac.html','#fb7185',true,80),
('algebra','ALG','Algebra','Matice, determinanty, sústavy rovníc, vektory a vlastné čísla.','pripravovane','subjects/algebra.html','#c084fc',true,90),
('praktikum','PRG','Praktikum z programovania','Java, OOP, ArrayList, triedy a školské zadania.','pripravovane','subjects/praktikum.html','#facc15',true,100),
('uvod','ÚDS','Úvod do štúdia','Semestrálna práca, UML, dokumentácia, plán a obhajoba.','pripravovane','subjects/uvod-do-studia.html','#2dd4bf',true,110)
on conflict (slug) do update set
  short_name = excluded.short_name,
  name = excluded.name,
  description = excluded.description,
  status = excluded.status,
  href = excluded.href,
  color = excluded.color,
  sort_order = excluded.sort_order,
  updated_at = now();

-- Po vytvorení svojho používateľa v Supabase Auth nastav jeho rolu:
-- update public.profiles
-- set role = 'admin'
-- where id = (select id from auth.users where email = 'tvoj@email.sk');
