/* StudyHub v2.1.1 — local admin editor. Server auth will replace this in Supabase phase. */
(function(){
"use strict";
var PASS="studyhub",SUBJECTS=[
{id:"vvs",name:"VVS",href:"subjects/vvs.html",status:"Rozpracované"},{id:"msd",name:"MSD",href:"subjects/msd.html",status:"Rozpracované"},{id:"mat",name:"Matematika",href:"subjects/mat.html",status:"Rozpracované"},{id:"ccna",name:"CCNA",href:"subjects/ccna.html",status:"Rozpracované"},{id:"linux",name:"Linux",href:"subjects/linux.html",status:"Hotové"},{id:"java",name:"Java",href:"subjects/java.html",status:"Rozpracované"},{id:"fyzika",name:"Fyzika",href:"subjects/fyzika.html",status:"Hotové"},{id:"tlac3d",name:"3D tlač",href:"subjects/3d-tlac.html",status:"Pripravované"},{id:"algebra",name:"Algebra",href:"subjects/algebra.html",status:"Pripravované"},{id:"praktikum",name:"Praktikum z programovania",href:"subjects/praktikum.html",status:"Pripravované"},{id:"uvod",name:"Úvod do štúdia",href:"subjects/uvod-do-studia.html",status:"Pripravované"}];
function ready(fn){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",fn);else fn()}
function get(k,f){try{var r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}
function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function uid(p){return p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,7)}
function toast(t,err){var e=document.querySelector(".admin-v21-toast");if(!e){e=document.createElement("div");e.className="admin-v21-toast";document.body.appendChild(e)}e.textContent=t;e.className="admin-v21-toast is-visible"+(err?" error":"");clearTimeout(toast.t);toast.t=setTimeout(function(){e.classList.remove("is-visible")},2400)}
function loginState(on){var l=document.getElementById("adminLogin"),c=document.getElementById("adminContent");if(l)l.classList.toggle("hidden",on);if(c)c.classList.toggle("hidden",!on);if(on){sessionStorage.setItem("studyHubAdminLoggedIn","1");sessionStorage.setItem("studyHubAdminUnlocked","true")}}
function login(){var input=document.getElementById("adminPasswordInput"),btn=document.getElementById("adminLoginBtn"),err=document.getElementById("adminLoginError");if(!input||!btn)return;if(sessionStorage.getItem("studyHubAdminLoggedIn")==="1"||sessionStorage.getItem("studyHubAdminUnlocked")==="true")loginState(true);function go(){var configured=localStorage.getItem("studyHubAdminPassword")||PASS;if(input.value===configured){if(err)err.classList.add("hidden");input.value="";loginState(true);toast("Admin prihlásenie úspešné.")}else{if(err)err.classList.remove("hidden");input.select()}}btn.addEventListener("click",go);input.addEventListener("keydown",function(e){if(e.key==="Enter")go()})}
function fills(){["materialSubject","questionSubject"].forEach(function(id){var s=document.getElementById(id);if(!s)return;var old=s.value;s.innerHTML="";SUBJECTS.forEach(function(x){var o=document.createElement("option");o.value=x.name;o.textContent=x.name;s.appendChild(o)});if(SUBJECTS.some(function(x){return x.name===old}))s.value=old})}
function answers(raw){return String(raw||"").split(/\r?\n/).map(function(x){return x.trim()}).filter(Boolean).map(function(x){var ok=x.charAt(0)==="*";return{text:ok?x.slice(1).trim():x,correct:ok}})}
function answerText(a){return Array.isArray(a)?a.map(function(x){return(x.correct?"*":"")+x.text}).join("\n"):""}
function materialForm(){var f=document.getElementById("materialForm");if(!f)return;f.addEventListener("submit",function(e){e.preventDefault();var title=document.getElementById("materialTitle").value.trim();if(!title){toast("Zadaj názov materiálu.",true);return}var list=get("studyHubAdminMaterials",[]),id=f.dataset.editId,item={id:id||uid("m"),subject:document.getElementById("materialSubject").value,title:title,type:document.getElementById("materialType").value,description:document.getElementById("materialDescription").value.trim(),updatedAt:new Date().toISOString()};if(id){var i=list.findIndex(function(x){return x.id===id});if(i>=0)list[i]=Object.assign({},list[i],item);delete f.dataset.editId;toast("Materiál upravený.")}else{item.createdAt=item.updatedAt;list.unshift(item);toast("Materiál uložený.")}set("studyHubAdminMaterials",list);f.reset();f.querySelector('button[type="submit"]').textContent="Uložiť materiál";fills();render("materials")})}
function questionForm(){var f=document.getElementById("questionForm");if(!f)return;f.addEventListener("submit",function(e){e.preventDefault();var q=document.getElementById("questionText").value.trim(),a=answers(document.getElementById("questionAnswers").value);if(!q){toast("Zadaj otázku.",true);return}if(a.length<2||!a.some(function(x){return x.correct})){toast("Zadaj aspoň 2 odpovede a správnu označ *.",true);return}var list=get("studyHubAdminQuestions",[]),id=f.dataset.editId,item={id:id||uid("q"),subject:document.getElementById("questionSubject").value,question:q,answers:a,explanation:document.getElementById("questionExplanation").value.trim(),updatedAt:new Date().toISOString()};if(id){var i=list.findIndex(function(x){return x.id===id});if(i>=0)list[i]=Object.assign({},list[i],item);delete f.dataset.editId;toast("Otázka upravená.")}else{item.createdAt=item.updatedAt;list.unshift(item);toast("Otázka uložená.")}set("studyHubAdminQuestions",list);f.reset();f.querySelector('button[type="submit"]').textContent="Uložiť otázku";fills();render("questions")})}
function render(tab){var host=document.getElementById("adminSavedContent");if(!host)return;tab=tab||"materials";document.querySelectorAll("[data-admin-tab]").forEach(function(b){b.classList.toggle("is-active",b.dataset.adminTab===tab)});var mats=get("studyHubAdminMaterials",[]),qs=get("studyHubAdminQuestions",[]),mc=document.getElementById("adminMaterialCount"),qc=document.getElementById("adminQuestionCount");if(mc)mc.textContent=mats.length;if(qc)qc.textContent=qs.length;var list=tab==="questions"?qs:mats;if(!list.length){host.innerHTML='<div class="admin-empty-state"><strong>Zatiaľ tu nič nie je.</strong><p>Pridaj prvú položku cez formulár.</p></div>';return}host.innerHTML="";list.forEach(function(item){var row=document.createElement("article");row.className="admin-saved-item";var title=tab==="questions"?item.question:item.title;row.innerHTML='<div><span></span><h3></h3><p></p></div><div class="admin-saved-actions"><button class="btn secondary" data-edit type="button">Upraviť</button><button class="btn secondary danger" data-delete type="button">Vymazať</button></div>';row.querySelector("span").textContent=[item.subject,tab==="questions"?"kvíz":item.type].filter(Boolean).join(" · ");row.querySelector("h3").textContent=title||"Bez názvu";row.querySelector("p").textContent=tab==="questions"?(item.explanation||"Bez vysvetlenia"):(item.description||"Bez popisu");row.querySelector("[data-delete]").addEventListener("click",function(){if(!confirm("Vymazať „"+title+"“?"))return;var key=tab==="questions"?"studyHubAdminQuestions":"studyHubAdminMaterials";set(key,get(key,[]).filter(function(x){return x.id!==item.id}));render(tab);toast("Položka vymazaná.")});row.querySelector("[data-edit]").addEventListener("click",function(){if(tab==="questions"){var f=document.getElementById("questionForm");f.dataset.editId=item.id;document.getElementById("questionSubject").value=item.subject;document.getElementById("questionText").value=item.question||"";document.getElementById("questionAnswers").value=answerText(item.answers);document.getElementById("questionExplanation").value=item.explanation||"";f.querySelector('button[type="submit"]').textContent="Uložiť zmeny otázky";f.scrollIntoView({behavior:"smooth",block:"center"})}else{var f2=document.getElementById("materialForm");f2.dataset.editId=item.id;document.getElementById("materialSubject").value=item.subject;document.getElementById("materialTitle").value=item.title||"";document.getElementById("materialType").value=item.type||"pdf";document.getElementById("materialDescription").value=item.description||"";f2.querySelector('button[type="submit"]').textContent="Uložiť zmeny materiálu";f2.scrollIntoView({behavior:"smooth",block:"center"})}});host.appendChild(row)})}
function tabs(){document.querySelectorAll("[data-admin-tab]").forEach(function(b){b.addEventListener("click",function(){render(b.dataset.adminTab)})});render("materials")}
function visibility(){var host=document.getElementById("subjectVisibilityAdmin");if(!host)return;function draw(){var v=get("studyHubSubjectVisibility",{});host.innerHTML="";SUBJECTS.forEach(function(s){var on=v[s.id]!==false,l=document.createElement("label");l.className="admin-subject-option";l.innerHTML='<span><input type="checkbox" data-subject-id="'+s.id+'" '+(on?"checked":"")+'></span><div><strong>'+s.name+'</strong><small>'+s.status+'</small></div><a href="'+s.href+'" target="_blank">Otvoriť →</a>';host.appendChild(l)});preview()}function current(){var o={};host.querySelectorAll("[data-subject-id]").forEach(function(x){o[x.dataset.subjectId]=x.checked});return o}function preview(){var v=host.querySelector("[data-subject-id]")?current():get("studyHubSubjectVisibility",{}),hidden=SUBJECTS.filter(function(s){return v[s.id]===false}),p=document.getElementById("hiddenSubjectsPreview");if(p)p.innerHTML="<strong>Skryté predmety:</strong> "+(hidden.length?hidden.map(function(s){return s.name}).join(", "):"žiadne")}draw();host.addEventListener("change",preview);var all=document.getElementById("selectAllSubjectsBtn"),none=document.getElementById("hideAllSubjectsBtn"),reset=document.getElementById("resetSubjectVisibilityBtn"),save=document.getElementById("saveSubjectVisibilityBtn");if(all)all.addEventListener("click",function(){host.querySelectorAll("input").forEach(function(x){x.checked=true});preview()});if(none)none.addEventListener("click",function(){host.querySelectorAll("input").forEach(function(x){x.checked=false});preview()});if(reset)reset.addEventListener("click",function(){localStorage.removeItem("studyHubSubjectVisibility");draw();toast("Viditeľnosť resetovaná.")});if(save)save.addEventListener("click",function(){set("studyHubSubjectVisibility",current());var s=document.getElementById("subjectVisibilityStatus");if(s)s.textContent="Uložené.";toast("Viditeľnosť predmetov uložená.")})}
function exportData(){var out=document.getElementById("adminOutput"),b=document.getElementById("exportBtn"),clear=document.getElementById("clearBtn");if(b&&out)b.addEventListener("click",function(){out.textContent=JSON.stringify({version:"2.1.1",exportedAt:new Date().toISOString(),materials:get("studyHubAdminMaterials",[]),questions:get("studyHubAdminQuestions",[]),subjectVisibility:get("studyHubSubjectVisibility",{})},null,2)});if(clear)clear.addEventListener("click",function(){if(!confirm("Vymazať lokálne admin dáta?"))return;["studyHubAdminMaterials","studyHubAdminQuestions","studyHubSubjectVisibility"].forEach(function(k){localStorage.removeItem(k)});render("materials");visibility();if(out)out.textContent="";toast("Lokálne admin dáta vymazané.")})}
ready(function(){login();fills();materialForm();questionForm();tabs();visibility();exportData()});
})();