/* StudyHub v2.1.1 enhancements: streak, live search, filters, mobile nav */
(function(){
"use strict";
function ready(fn){if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",fn);else fn()}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\s+/g," ").trim()}
function json(k,f){try{var r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}
function subjectPage(){return location.pathname.replace(/\\/g,"/").includes("/subjects/")}
function root(){return subjectPage()?"../":""}function url(p){if(!p)return"#";if(/^(https?:|mailto:|tel:|#)/i.test(p))return p;return root()+p.replace(/^\.\//,"")}
function dateKey(d){d=d||new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function diff(a,b){return Math.round((new Date(b+"T12:00:00")-new Date(a+"T12:00:00"))/86400000)}
function activityPage(){var f=(location.pathname.split("/").pop()||"index.html").toLowerCase();return subjectPage()||["","index.html","subjects.html","flashcards.html","results.html"].includes(f)}
function streak(){
 var d=json("studyHubStreakData",{current:0,best:0,lastDate:"",days:[]});if(!Array.isArray(d.days))d.days=[];var today=dateKey();
 if(activityPage()&&d.lastDate!==today){if(!d.lastDate)d.current=1;else d.current=diff(d.lastDate,today)===1?(Number(d.current)||0)+1:1;d.lastDate=today;if(!d.days.includes(today))d.days.push(today);d.days=d.days.slice(-120);d.best=Math.max(Number(d.best)||0,Number(d.current)||0);localStorage.setItem("studyHubStreakData",JSON.stringify(d));localStorage.setItem("studyHubStreak",String(d.current))}
 function form(n){return n===1?" deň":n>=2&&n<=4?" dni":" dní"}document.querySelectorAll("#v2StudyStreak,#v21StreakCurrent").forEach(function(x){x.textContent=(Number(d.current)||0)+form(Number(d.current)||0)});var b=document.getElementById("v21StreakBest");if(b)b.textContent=(Number(d.best)||0)+form(Number(d.best)||0);
 var h=document.getElementById("v21StreakDays");if(h){h.innerHTML="";var set=new Set(d.days);for(var o=27;o>=0;o--){var dt=new Date();dt.setHours(12,0,0,0);dt.setDate(dt.getDate()-o);var k=dateKey(dt),s=document.createElement("span");if(set.has(k))s.classList.add("is-active");if(k===today)s.classList.add("is-today");s.title=k+(set.has(k)?" – aktivita":" – bez aktivity");h.appendChild(s)}}
}
function runtimeIndex(){
 var a=Array.isArray(window.STUDYHUB_SEARCH_INDEX)?window.STUDYHUB_SEARCH_INDEX.slice():[],routes={Linux:"subjects/linux.html",MSD:"subjects/msd.html",CCNA:"subjects/ccna.html",VVS:"subjects/vvs.html",Matematika:"subjects/mat.html",Java:"subjects/java.html",Fyzika:"subjects/fyzika.html",Algebra:"subjects/algebra.html","3D tlač":"subjects/3d-tlac.html","Praktikum z programovania":"subjects/praktikum.html","Úvod do štúdia":"subjects/uvod-do-studia.html"};
 json("studyHubAdminMaterials",[]).forEach(function(x){a.push({title:x.title||"Materiál",type:x.type==="zadanie"?"Zadanie":x.type==="kviz"?"Kvíz":x.type==="pdf"?"PDF":"Poznámka",url:(routes[x.subject]||"subjects.html")+"#admin-local-content",subject:x.subject||"",keywords:x.description||"",snippet:x.description||"Admin materiál"})});
 json("studyHubAdminQuestions",[]).forEach(function(x){a.push({title:x.question||"Otázka",type:"Kvíz",url:(routes[x.subject]||"results.html")+"#admin-local-content",subject:x.subject||"",keywords:x.explanation||"",snippet:x.explanation||"Admin otázka"})});return a
}
function liveSearch(){
 var form=document.querySelector(".v2-global-search"),input=form&&form.querySelector("input");if(!form||!input)return;var box=form.querySelector(".v21-search-results");if(!box){box=document.createElement("div");box.className="v21-search-results";box.hidden=true;form.appendChild(box)}
 function close(){box.hidden=true;box.innerHTML=""}
 function render(){var q=norm(input.value);if(q.length<2){close();return}var words=q.split(" ").filter(Boolean),matches=runtimeIndex().map(function(i){var t=norm([i.title,i.type,i.subject,i.keywords,i.snippet].join(" "));if(!words.every(function(w){return t.includes(w)}))return null;var title=norm(i.title),score=title===q?100:title.startsWith(q)?55:title.includes(q)?30:norm(i.subject).includes(q)?15:1;return{i:i,s:score}}).filter(Boolean).sort(function(a,b){return b.s-a.s}).slice(0,80);
 if(!matches.length){box.innerHTML='<div class="v21-search-empty"><strong>Nič sa nenašlo</strong><span>Skús iný názov, predmet alebo tému.</span></div>';box.hidden=false;return}
 var order=["Predmet","Téma","Poznámka","Zadanie","Kvíz","PDF","Flashcards"],g={};matches.forEach(function(r){var t=r.i.type||"Téma";(g[t]||(g[t]=[])).push(r.i)});var html='<div class="v21-search-summary">Výsledky pre <strong>'+input.value.replace(/[<>]/g,"")+'</strong><span>'+matches.length+' nájdených</span></div>';order.concat(Object.keys(g).filter(function(k){return !order.includes(k)})).forEach(function(t){var list=g[t];if(!list)return;html+='<section class="v21-search-group"><h3>'+t+'<span>'+list.length+'</span></h3>';list.slice(0,6).forEach(function(i){html+='<a class="v21-search-item" href="'+url(i.url)+'"><span class="v21-search-type">'+t.charAt(0)+'</span><div><strong>'+String(i.title||"").replace(/[<>]/g,"")+'</strong><small>'+[i.subject,i.snippet].filter(Boolean).join(" · ").replace(/[<>]/g,"")+'</small></div><b>→</b></a>'});html+='</section>'});box.innerHTML=html;box.hidden=false}
 input.addEventListener("input",render);input.addEventListener("focus",function(){if(input.value.trim().length>=2)render()});input.addEventListener("keydown",function(e){if(e.key==="Escape"){close();input.blur()}});document.addEventListener("click",function(e){if(!form.contains(e.target))close()});form.addEventListener("submit",function(e){e.preventDefault();e.stopImmediatePropagation();var a=box.querySelector("a");if(a)location.href=a.href;else render()},true)
}
function filters(){
 if(!document.body.classList.contains("page-subjects"))return;var input=document.getElementById("subjectFilterInput"),reset=document.getElementById("subjectFilterReset"),count=document.getElementById("subjectFilterCount"),empty=document.getElementById("subjectFilterEmpty"),chips=[].slice.call(document.querySelectorAll("[data-status-filter]")),cards=[].slice.call(document.querySelectorAll(".subject-card[data-subject-id]")),status="all";if(!cards.length)return;
 function apply(){var q=norm(input?input.value:""),visible=0,allowed=0;cards.forEach(function(c){var admin=c.getAttribute("data-visibility-hidden")!=="true";if(admin)allowed++;var text=norm((c.getAttribute("data-search")||"")+" "+c.textContent),tm=!q||q.split(" ").every(function(w){return text.includes(w)}),sm=status==="all"||c.getAttribute("data-status")===status,show=admin&&tm&&sm;c.hidden=!show;c.classList.toggle("is-filtered-out",!show);if(show)visible++});if(count)count.textContent="Zobrazené predmety: "+visible+" / "+allowed;if(empty)empty.hidden=visible!==0}
 chips.forEach(function(c){c.addEventListener("click",function(e){e.stopImmediatePropagation();status=c.getAttribute("data-status-filter")||"all";chips.forEach(function(x){x.classList.toggle("active",x===c)});apply()},true)});if(input)input.addEventListener("input",function(e){e.stopImmediatePropagation();apply()},true);if(reset)reset.addEventListener("click",function(e){e.stopImmediatePropagation();if(input)input.value="";status="all";chips.forEach(function(x){x.classList.toggle("active",x.getAttribute("data-status-filter")==="all")});apply()},true);document.addEventListener("studyhub:subject-visibility-changed",apply);var incoming=new URLSearchParams(location.search).get("search");if(incoming&&input)input.value=incoming;setTimeout(apply,0)
}
function mobileNav(){
 if(document.querySelector(".v21-mobile-bottom-nav"))return;var n=document.createElement("nav");n.className="v21-mobile-bottom-nav";var items=[["index.html","⌂","Domov"],["subjects.html","▦","Predmety"],["flashcards.html","▣","Flashcards"],["results.html","▥","Výsledky"]],current=(location.pathname.split("/").pop()||"index.html").toLowerCase();items.forEach(function(i){var a=document.createElement("a");a.href=url(i[0]);a.innerHTML="<span>"+i[1]+"</span><small>"+i[2]+"</small>";if(current===i[0]||(i[0]==="subjects.html"&&subjectPage()))a.classList.add("is-active");n.appendChild(a)});document.body.appendChild(n)
}
function subjectName(){var f=(location.pathname.split("/").pop()||"").toLowerCase(),m={"linux.html":"Linux","msd.html":"MSD","ccna.html":"CCNA","vvs.html":"VVS","mat.html":"Matematika","java.html":"Java","fyzika.html":"Fyzika","algebra.html":"Algebra","3d-tlac.html":"3D tlač","praktikum.html":"Praktikum z programovania","uvod-do-studia.html":"Úvod do štúdia"};return m[f]||""}
function adminContent(){
 if(!subjectPage())return;var s=subjectName();if(!s)return;var mats=json("studyHubAdminMaterials",[]).filter(function(x){return x.subject===s}),qs=json("studyHubAdminQuestions",[]).filter(function(x){return x.subject===s});if(!mats.length&&!qs.length)return;var host=document.querySelector(".subject-content .container")||document.querySelector("main .container");if(!host||document.getElementById("admin-local-content"))return;var sec=document.createElement("section");sec.className="content-block";sec.id="admin-local-content";sec.innerHTML='<p class="small-title">Admin obsah</p><h2>Pridané cez Admin editor</h2><div class="v21-admin-content-grid"></div>';var g=sec.querySelector(".v21-admin-content-grid");mats.forEach(function(x){var c=document.createElement("article");c.className="v21-local-card";c.innerHTML="<span>"+(x.type||"materiál")+"</span><h3></h3><p></p>";c.querySelector("h3").textContent=x.title||"Materiál";c.querySelector("p").textContent=x.description||"Bez popisu";g.appendChild(c)});qs.forEach(function(x){var c=document.createElement("article");c.className="v21-local-card";c.innerHTML="<span>Kvíz</span><h3></h3><p></p>";c.querySelector("h3").textContent=x.question||"Otázka";c.querySelector("p").textContent=x.explanation||"Bez vysvetlenia";g.appendChild(c)});host.appendChild(sec)
}
ready(function(){streak();liveSearch();filters();mobileNav();adminContent()});
})();